=== icyphy/ptweb/trunk/ptweb/xml/dtd/MoML_1.dtd
<!-- MoML DTD Version 1.3, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->
<!-- NOTE: To ensure backward compatibility with other version 1.x DTDs, -->
<!-- there are quite a few deprecated entries here. The documentation    -->
<!-- does not mention these deprecated entries. -->

<!-- The model element is deprecated.  Use entity instead. -->
<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | doc | entity | group | import |
                input | link | property | relation | rename | rendition |
		unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | doc |
                 entity | group | import | input | link | port |
                 property | relation | rename | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED
		source CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!-- NOTE: deprecated.  Use property instead. -->
<!ELEMENT director (configure | doc | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA #IMPLIED>

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | doc |
                  entity | group | import | input | link | port |
                  property | relation | rename | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED
		 source CDATA #IMPLIED>

<!ELEMENT group ANY>
<!ATTLIST group name CDATA #IMPLIED>

<!-- The import element is deprecated.  Use the source attribute instead. -->
<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!-- The base attribute is deprecated. -->
<!ELEMENT input EMPTY>
<!ATTLIST input source CDATA #REQUIRED
                base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               insertInsideAt CDATA #IMPLIED
               port CDATA #IMPLIED
               relation CDATA #IMPLIED
               relation1 CDATA #IMPLIED
               relation2 CDATA #IMPLIED
               vertex CDATA #IMPLIED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | doc | property | rename)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | doc | property | rename)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (configure | doc | property | rename | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rename EMPTY>
<!ATTLIST rename name CDATA #REQUIRED>

<!-- Deprecated.  Use a property instead. -->
<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
                 port CDATA #IMPLIED
                 relation1 CDATA #IMPLIED
                 relation2 CDATA #IMPLIED
                 relation CDATA #IMPLIED>

<!ELEMENT vertex (configure | doc | location | property | rename)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED
                 value CDATA #IMPLIED>

=== icyphy/ptweb/trunk/ptweb/xml/models/Waveform.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE class PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<class name="Sinewave" extends="ptolemy.actor.TypedCompositeActor">
    <doc>This composite actor generates a sine wave.</doc>
    <property name="samplingFrequency" class="ptolemy.data.expr.Parameter" value="8000.0">
        <doc>The sampling frequency, in the same units as the frequency.</doc>
    </property>
    <property name="frequency" class="ptolemy.data.expr.Parameter" value="440.0">
        <doc>The frequency of the sinusoid, in the same units as the sampling frequency.</doc>
    </property>
    <property name="phase" class="ptolemy.data.expr.Parameter" value="0.0">
        <doc>The phase, in radians.</doc>
    </property>
    <port name="output" class="ptolemy.actor.TypedIOPort">
        <property name="output"/>
        <doc>Sinusoidal waveform output.</doc>
        <property name="_location" class="ptolemy.moml.Location" value="496.00001525878906, 120.00000381469727">
        </property>
    </port>
    <entity name="Ramp" class="ptolemy.actor.lib.Ramp">
        <property name="firingCountLimit" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="init" class="ptolemy.data.expr.Parameter" value="phase">
        </property>
        <property name="step" class="ptolemy.data.expr.Parameter" value="frequency*2*PI/samplingFrequency">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="95.0, 99.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="Sine Function" class="ptolemy.actor.lib.TrigFunction">
        <property name="function" class="ptolemy.kernel.util.StringAttribute" value="sin">
            <property name="style" class="ptolemy.actor.gui.style.ChoiceStyle">
                <property name="acos" class="ptolemy.kernel.util.StringAttribute" value="acos">
                </property>
                <property name="asin" class="ptolemy.kernel.util.StringAttribute" value="asin">
                </property>
                <property name="atan" class="ptolemy.kernel.util.StringAttribute" value="atan">
                </property>
                <property name="cos" class="ptolemy.kernel.util.StringAttribute" value="cos">
                </property>
                <property name="sin" class="ptolemy.kernel.util.StringAttribute" value="sin">
                </property>
                <property name="tan" class="ptolemy.kernel.util.StringAttribute" value="tan">
                </property>
            </property>
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="218.0, 91.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="MathFunction0" class="ptolemy.actor.lib.MathFunction">
        <property name="function" class="ptolemy.kernel.util.StringAttribute" value="square">
            <property name="style" class="ptolemy.actor.gui.style.ChoiceStyle">
                <property name="exp" class="ptolemy.kernel.util.StringAttribute" value="exp">
                </property>
                <property name="log" class="ptolemy.kernel.util.StringAttribute" value="log">
                </property>
                <property name="remainder" class="ptolemy.kernel.util.StringAttribute" value="remainder">
                </property>
                <property name="sign" class="ptolemy.kernel.util.StringAttribute" value="sign">
                </property>
                <property name="square" class="ptolemy.kernel.util.StringAttribute" value="square">
                </property>
                <property name="sqrt" class="ptolemy.kernel.util.StringAttribute" value="sqrt">
                </property>
            </property>
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="330.0, 102.0">
        </property>
        <port name="firstOperand" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="AddSubtract4" class="ptolemy.actor.lib.AddSubtract">
        <property name="_location" class="ptolemy.moml.Location" value="425.0, 115.0">
        </property>
        <port name="plus" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
        <port name="minus" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="Gaussian7" class="ptolemy.actor.lib.Gaussian">
        <property name="seed" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="mean" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <property name="standardDeviation" class="ptolemy.data.expr.Parameter" value="0.05">
        </property>
        <doc>Create a sequence of gaussian random variables</doc>
        <property name="_location" class="ptolemy.moml.Location" value="306.0, 173.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation5" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation6" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation8" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="output" relation="relation6"/>
    <link port="Ramp.output" relation="relation2"/>
    <link port="Sine Function.input" relation="relation2"/>
    <link port="Sine Function.output" relation="relation3"/>
    <link port="MathFunction0.firstOperand" relation="relation3"/>
    <link port="MathFunction0.output" relation="relation5"/>
    <link port="AddSubtract4.plus" relation="relation5"/>
    <link port="AddSubtract4.minus" relation="relation8"/>
    <link port="AddSubtract4.output" relation="relation6"/>
    <link port="Gaussian7.output" relation="relation8"/>
</class>
